export const category = [
  { value: "province", label: "Province" },
  { value: "district", label: "District" },
  { value: "tehsil", label: "Tehsil" },
];

export const provinces = [
  {
    value: "azad kashmir",
    label: "Azad Kashmir",
  },
  {
    value: "balochistan",
    label: "Balochistan",
  },
  {
    value: "sindh",
    label: "Sindh",
  },
  {
    value: "khyber pakhtunkhwa",
    label: "KPK",
  },
  {
    value: "gilgit baltistan",
    label: "Gilgit Baltistan",
  },
  {
    value: "punjab",
    label: "Punjab",
  },
  {
    value: "islamabad",
    label: "Islamabad",
  },
];

export const educationLevels = [
  { value: "matric", label: "Matric" },
  { value: "fsc", label: "FSC" },
  { value: "bachelor", label: "Bachelor's" },
  { value: "master", label: "Master's" },
  { value: "phd", label: "PhD" },
];

export const experienceOptions = [
  { value: "0-1", label: "0-1 year" },
  { value: "1-3", label: "1-3 years" },
  { value: "3-5", label: "3-5 years" },
  { value: "5-10", label: "5-10 years" },
  { value: "10+", label: "10+ years" },
];

export const tradeOptions = [
  { value: "carpenter", label: "Carpenter" },
  { value: "elevator_mechanic", label: "Elevator Mechanic" },
  { value: "iron_worker", label: "Iron Worker" },
  { value: "laborer", label: "Laborer" },
  { value: "civil_engineer", label: "Civil Engineer" },
  { value: "mechanical", label: "Mechanical" },
  { value: "electrical", label: "Electrical" },
  { value: "electronics", label: "Electronics" },
  { value: "chemical", label: "Chemical" },
  { value: "mechatronics", label: "Mechatronics" },
  { value: "printing_graphic_arts", label: "Printing and Graphic Arts" },
  { value: "electrical_automation", label: "Electrical Automation" },
  {
    value: "land_survey_management",
    label: "Land and Resources Survey & Management",
  },
  {
    value: "water_hydropower",
    label: "Water Resources and Hydropower Construction",
  },
  { value: "coal_mining", label: "Coal and Mining" },
  { value: "plumber", label: "Plumber" },
  { value: "solar_plumber", label: "Final Plumber with Solar Water Heating" },
  { value: "multi_welder", label: "Advance Multi Welder" },
  { value: "welder", label: "Welder" },
  { value: "electrical_power", label: "Electrical Power System" },
  {
    value: "appliance_technician",
    label: "Domestic Electrical Appliance Technician",
  },
  { value: "hybrid_vehicles", label: "Intelligent Hybrid Electric Vehicles" },
  { value: "general_electrician", label: "General Electrician" },
  { value: "arc_welding", label: "Electric Arc Welding" },
  { value: "industrial_electrician", label: "Industrial Electrician" },
  { value: "auto_cad", label: "Advanced Auto CAD" },
  { value: "mason", label: "Mason" },
  { value: "building_painter", label: "Building Painter" },
  { value: "shuttering_scaffolding", label: "Shuttering Scaffolding" },
  { value: "steel_fixer", label: "Steel Fixer" },
];

export const role = [
  { value: "m&e", label: "M&E" },
  { value: "apprenticeship", label: "Apprenticeship" },
];

export const districts = [
  { value: "north waziristan", label: "North Waziristan" },
  { value: "rawalpindi", label: "Rawalpindi" },
  { value: "rajanpur", label: "Rajanpur" },
  { value: "bajaur", label: "Bajaur" },
  { value: "badin", label: "Badin" },
  { value: "torghar", label: "Torghar" },
  { value: "mirpur khas", label: "Mirpur Khas" },
  { value: "tharparkar", label: "Tharparkar" },
  { value: "mirpur", label: "Mirpur" },
  { value: "chakwal", label: "Chakwal" },
  { value: "skardu", label: "Skardu" },
  { value: "diamir", label: "Diamir" },
  { value: "upper chitral", label: "Upper Chitral" },
  { value: "tank", label: "Tank" },
  { value: "lower dir", label: "Lower Dir" },
  { value: "murree", label: "Murree" },
  { value: "larkana", label: "Larkana" },
  { value: "peshawar", label: "Peshawar" },
  { value: "barkhan", label: "Barkhan" },
  { value: "mardan", label: "Mardan" },
  { value: "hafizabad", label: "Hafizabad" },
  { value: "gujrat", label: "Gujrat" },
  { value: "khushab", label: "Khushab" },
  { value: "matiari", label: "Matiari" },
  { value: "khuzdar", label: "Khuzdar" },
  { value: "ghizer", label: "Ghizer" },
  { value: "harnai", label: "Harnai" },
  { value: "kohat", label: "Kohat" },
  { value: "lodhran", label: "Lodhran" },
  { value: "darel", label: "Darel" },
  { value: "bahawalnagar", label: "Bahawalnagar" },
  { value: "kalat", label: "Kalat" },
  { value: "dera ismail khan", label: "Dera Ismail Khan" },
  { value: "lower kohistan", label: "Lower Kohistan" },
  { value: "talagang", label: "Talagang" },
  { value: "washuk", label: "Washuk" },
  { value: "sibi", label: "Sibi" },
  { value: "gujranwala", label: "Gujranwala" },
  { value: "jamshoro", label: "Jamshoro" },
  { value: "karak", label: "Karak" },
  { value: "bhimber", label: "Bhimber" },
  { value: "rahim yar khan", label: "Rahim Yar Khan" },
  { value: "lasbela", label: "Lasbela" },
  { value: "malakand", label: "Malakand" },
  { value: "jhang", label: "Jhang" },
  { value: "layyah", label: "Layyah" },
  { value: "jhal magsi", label: "Jhal Magsi" },
  { value: "muzaffarabad", label: "Muzaffarabad" },
  { value: "lower chitral", label: "Lower Chitral" },
  { value: "kharan", label: "Kharan" },
  { value: "zhob", label: "Zhob" },
  { value: "sudhnoti", label: "Sudhnoti" },
  { value: "kolai-palas", label: "Kolai-Palas" },
  { value: "musakhel", label: "Musakhel" },
  { value: "dadu", label: "Dadu" },
  { value: "upper dir", label: "Upper Dir" },
  { value: "gilgit", label: "Gilgit" },
  { value: "kasur", label: "Kasur" },
  { value: "keamari", label: "Keamari" },
  { value: "bannu", label: "Bannu" },
  { value: "khairpur mirs", label: "Khairpur Mirs" },
  { value: "jampur", label: "Jampur" },
  { value: "sahiwal", label: "Sahiwal" },
  { value: "kech", label: "Kech" },
  { value: "lower south waziristan", label: "Lower South Waziristan" },
  { value: "hattian bala", label: "Hattian Bala" },
  { value: "sherani", label: "Sherani" },
  { value: "tando allahyar", label: "Tando Allahyar" },
  { value: "sohbatpur", label: "Sohbatpur" },
  { value: "qambar-shahdadkot", label: "Qambar-Shahdadkot" },
  { value: "astore", label: "Astore" },
  { value: "wazirabad", label: "Wazirabad" },
  { value: "tando muhammad khan", label: "Tando Muhammad Khan" },
  { value: "gwadar", label: "Gwadar" },
  { value: "kurram", label: "Kurram" },
  { value: "shigar", label: "Shigar" },
  { value: "killa saifullah", label: "Killa Saifullah" },
  { value: "ziarat", label: "Ziarat" },
  { value: "dera bugti", label: "Dera Bugti" },
  { value: "khanewal", label: "Khanewal" },
  { value: "abbottabad", label: "Abbottabad" },
  { value: "umerkot", label: "Umerkot" },
  { value: "karachi south", label: "Karachi South" },
  { value: "nankana sahib", label: "Nankana Sahib" },
  { value: "hyderabad", label: "Hyderabad" },
  { value: "toba tek singh", label: "Toba Tek Singh" },
  { value: "sheikhupura", label: "Sheikhupura" },
  { value: "ghotki", label: "Ghotki" },
  { value: "killa abdullah", label: "Killa Abdullah" },
  { value: "bhakkar", label: "Bhakkar" },
  { value: "poonch", label: "Poonch" },
  { value: "charsadda", label: "Charsadda" },
  { value: "upper south waziristan", label: "Upper South Waziristan" },
  { value: "vehari", label: "Vehari" },
  { value: "nasirabad", label: "Nasirabad" },
  { value: "naushahro feroze", label: "Naushahro Feroze" },
  { value: "khyber", label: "Khyber" },
  { value: "mandi bahauddin", label: "Mandi Bahauddin" },
  { value: "nagar", label: "Nagar" },
  { value: "loralai", label: "Loralai" },
  { value: "taunsa", label: "Taunsa" },
  { value: "sialkot", label: "Sialkot" },
  { value: "quetta", label: "Quetta" },
  { value: "faisalabad", label: "Faisalabad" },
  { value: "bagh", label: "Bagh" },
  { value: "attock", label: "Attock" },
  { value: "tangir", label: "Tangir" },
  { value: "duki", label: "Duki" },
  { value: "jhelum", label: "Jhelum" },
  { value: "rondu", label: "Rondu" },
  { value: "pishin", label: "Pishin" },
  { value: "chagai", label: "Chagai" },
  { value: "korangi", label: "Korangi" },
  { value: "mansehra", label: "Mansehra" },
  { value: "lahore", label: "Lahore" },
  { value: "dera ghazi khan", label: "Dera Ghazi Khan" },
  { value: "karachi west", label: "Karachi West" },
  { value: "nushki", label: "Nushki" },
  { value: "orakzai", label: "Orakzai" },
  { value: "kachi", label: "Kachi" },
  { value: "hunza", label: "Hunza" },
  { value: "sukkur", label: "Sukkur" },
  { value: "karachi central", label: "Karachi Central" },
  { value: "gupis-yasin", label: "Gupis-Yasin" },
  { value: "shangla", label: "Shangla" },
  { value: "kot addu", label: "Kot Addu" },
  { value: "malir", label: "Malir" },
  { value: "kohlu", label: "Kohlu" },
  { value: "karachi east", label: "Karachi East" },
  { value: "swat", label: "Swat" },
  { value: "kashmore", label: "Kashmore" },
  { value: "sanghar", label: "Sanghar" },
  { value: "bahawalpur", label: "Bahawalpur" },
  { value: "haripur", label: "Haripur" },
  { value: "neelum", label: "Neelum" },
  { value: "batagram", label: "Batagram" },
  { value: "sujawal", label: "Sujawal" },
  { value: "hangu", label: "Hangu" },
  { value: "lakki marwat", label: "Lakki Marwat" },
  { value: "shikarpur", label: "Shikarpur" },
  { value: "okara", label: "Okara" },
  { value: "nowshera", label: "Nowshera" },
  { value: "awaran", label: "Awarn" },
  { value: "jafarabad", label: "Jafarabad" },
  { value: "thatta", label: "Thatta" },
  { value: "jacobabad", label: "Jacobabad" },
  { value: "multan", label: "Multan" },
  { value: "swabi", label: "Swabi" },
  { value: "haveli", label: "Haveli" },
  { value: "buner", label: "Buner" },
  { value: "sargodha", label: "Sargodha" },
  { value: "panjgur", label: "Panjgur" },
  { value: "kharmang", label: "Kharmang" },
  { value: "mohmand", label: "Mohmand" },
  { value: "mianwali", label: "Mianwali" },
  { value: "muzaffargarh", label: "Muzaffargarh" },
  { value: "shaheed benazir abad", label: "Shaheed Benazir Abad" },
  { value: "lehri", label: "Lehri" },
  { value: "mastung", label: "Mastung" },
  { value: "pakpattan", label: "Pakpattan" },
  { value: "narowal", label: "Narowal" },
  { value: "upper kohistan", label: "Upper Kohistan" },
  { value: "ghanche", label: "Ghanche" },
  { value: "chiniot", label: "Chiniot" },
];

export const tehsils = [
  { value: "bahawalnagar", label: "Bahawalnagar" },
  { value: "chishtian", label: "Chishtian" },
  { value: "fort abbas", label: "Fort Abbas" },
  { value: "haroonabad", label: "Haroonabad" },
  { value: "minchinabad", label: "Minchinabad" },
  { value: "ahmadpur east", label: "Ahmadpur East" },
  { value: "bahawalpur city", label: "Bahawalpur City" },
  { value: "bahawalpur saddar", label: "Bahawalpur Saddar" },
  { value: "hasilpur", label: "Hasilpur" },
  { value: "khairpur tamewali", label: "Khairpur Tamewali" },
  { value: "yazman", label: "Yazman" },
  { value: "khanpur", label: "Khanpur" },
  { value: "liaqatpur", label: "Liaqatpur" },
  { value: "rahim yar khan", label: "Rahim Yar Khan" },
  { value: "sadiqabad", label: "Sadiqabad" },
  { value: "dera ghazi khan", label: "Dera Ghazi Khan" },
  { value: "jampur", label: "Jampur" },
  { value: "muhammadpur", label: "Muhammadpur" },
  { value: "dajal", label: "Dajal" },
  { value: "tribal area", label: "Tribal Area" },
  { value: "kot addu", label: "Kot Addu" },
  { value: "chowk sarwar shaheed", label: "Chowk Sarwar Shaheed" },
  { value: "chaubara", label: "Chaubara" },
  { value: "karor lal esan", label: "Karor Lal Esan" },
  { value: "layyah", label: "Layyah" },
  { value: "alipur", label: "Alipur" },
  { value: "jatoi", label: "Jatoi" },
  { value: "muzaffargarh", label: "Muzaffargarh" },
  { value: "rojhan", label: "Rojhan" },
  { value: "taunsa", label: "Taunsa" },
  { value: "koh-e-suleman", label: "Koh-e-Suleman" },
  { value: "vehova", label: "Vehova" },
  { value: "bhowana", label: "Bhowana" },
  { value: "chiniot", label: "Chiniot" },
  { value: "lalian", label: "Lalian" },
  { value: "chak jhumra", label: "Chak Jhumra" },
  { value: "faisalabad city", label: "Faisalabad City" },
  { value: "faisalabad sadar", label: "Faisalabad Sadar" },
  { value: "jaranwala", label: "Jaranwala" },
  { value: "samundri", label: "Samundri" },
  { value: "tandlianwala", label: "Tandlianwala" },
  { value: "jhang", label: "Jhang" },
  { value: "shorkot", label: "Shorkot" },
  { value: "ahmadpur sial", label: "Ahmadpur Sial" },
  { value: "athara hazari", label: "Athara Hazari" },
  { value: "gojra", label: "Gojra" },
  { value: "kamalia", label: "Kamalia" },
  { value: "pirmahal", label: "Pirmahal" },
  { value: "toba tek singh", label: "Toba Tek Singh" },
  { value: "gujrat", label: "Gujrat" },
  { value: "kharian", label: "Kharian" },
  { value: "sarai alamgir", label: "Sarai Alamgir" },
  { value: "jalalpur jattan", label: "Jalalpur Jattan" },
  { value: "kunjah", label: "Kunjah" },
  { value: "hafizabad", label: "Hafizabad" },
  { value: "pindi bhattian", label: "Pindi Bhattian" },
  { value: "malakwal", label: "Malakwal" },
  { value: "mandi bahauddin", label: "Mandi Bahauddin" },
  { value: "phalia", label: "Phalia" },
  { value: "wazirabad", label: "Wazirabad" },
  { value: "ali pur chatta", label: "Ali Pur Chatta" },
  { value: "gujranwala city", label: "Gujranwala City" },
  { value: "gujranwala saddar", label: "Gujranwala Saddar" },
  { value: "kamoke", label: "Kamoke" },
  { value: "daghoni", label: "Daghoni" },
  { value: "khaplu", label: "Khaplu" },
  { value: "mashabrum", label: "Mashabrum" },
  { value: "chorbut", label: "Chorbut" },
  { value: "keris", label: "Keris" },
  { value: "haldi", label: "Haldi" },
  { value: "shigar", label: "Shigar" },
  { value: "gulabpur", label: "Gulabpur" },
  { value: "gultari", label: "Gultari" },
  { value: "skardu", label: "Skardu" },
  { value: "gamba", label: "Gamba" },
  { value: "rondu", label: "Rondu" },
  { value: "astore", label: "Astore" },
  { value: "shounter", label: "Shounter" },
  { value: "babusar", label: "Babusar" },
  { value: "punial", label: "Punial" },
  { value: "ishkoman", label: "Ishkoman" },
  { value: "danyor", label: "Danyor" },
  { value: "gilgit", label: "Gilgit" },
  { value: "juglot", label: "Juglot" },
  { value: "rondu", label: "Rondu" },
  { value: "chilas", label: "Chilas" },
  { value: "darel", label: "Darel" },
  { value: "mandi shah jeewna", label: "Mandi Shah Jeewna" },
  { value: "jampur", label: "Jampur" },
  { value: "fazilpur", label: "Fazilpur" },
  { value: "tangir", label: "Tangir" },
  { value: "nowshera virkan", label: "Nowshera Virkan" },
  { value: "narowal", label: "Narowal" },
  { value: "shakargarh", label: "Shakargarh" },
  { value: "zafarwal", label: "Zafarwal" },
  { value: "daska", label: "Daska" },
  { value: "pasrur", label: "Pasrur" },
  { value: "sambrial", label: "Sambrial" },
  { value: "sialkot", label: "Sialkot" },
  { value: "chunian", label: "Chunian" },
  { value: "kasur", label: "Kasur" },
  { value: "kot radha kishan", label: "Kot Radha Kishan" },
  { value: "pattoki", label: "Pattoki" },
  { value: "lahore cantonment", label: "Lahore Cantonment" },
  { value: "lahore city", label: "Lahore City" },
  { value: "model town", label: "Model Town" },
  { value: "raiwind", label: "Raiwind" },
  { value: "shalimar", label: "Shalimar" },
  { value: "nankana sahib", label: "Nankana Sahib" },
  { value: "sangla hill", label: "Sangla Hill" },
  { value: "shah kot", label: "Shah Kot" },
  { value: "ferozewala", label: "Ferozewala" },
  { value: "muridke", label: "Muridke" },
  { value: "safdarabad", label: "Safdarabad" },
  { value: "sheikhupura", label: "Sheikhupura" },
  { value: "sharak pur", label: "Sharak Pur" },
  { value: "jahanian", label: "Jahanian" },
  { value: "kabirwala", label: "Kabirwala" },
  { value: "khanewal", label: "Khanewal" },
  { value: "mian channu", label: "Mian Channu" },
  { value: "rahimyaar khan", label: "Rahimyar Khan" },
  { value: "dunyapur", label: "Dunyapur" },
  { value: "kahror pacca", label: "Kahror Pacca" },
  { value: "lodhran", label: "Lodhran" },
  { value: "jalalpur pirwala", label: "Jalalpur Pirwala" },
  { value: "multan city", label: "Multan City" },
  { value: "multan saddar", label: "Multan Saddar" },
  { value: "shujabad", label: "Shujabad" },
  { value: "burewala", label: "Burewala" },
  { value: "mailsi", label: "Mailsi" },
  { value: "vehari", label: "Vehari" },
  { value: "jallah jeem", label: "Jallah Jeem" },
  { value: "attock", label: "Attock" },
  { value: "fateh jang", label: "Fateh Jang" },
  { value: "hassan abdal", label: "Hassan Abdal" },
  { value: "hazro", label: "Hazro" },
  { value: "jand", label: "Jand" },
  { value: "pindi gheb", label: "Pindi Gheb" },
  { value: "chakwal", label: "Chakwal" },
  { value: "choa saidan shah", label: "Choa Saidanshah" },
  { value: "kallar kahar", label: "Kallar Kahar" },
  { value: "dina", label: "Dina" },
  { value: "jhelum", label: "Jhelum" },
  { value: "pind dadan khan", label: "Pind Dadan Khan" },
  { value: "sohawa", label: "Sohawa" },
  { value: "rawalpindi", label: "Rawalpindi" },
  { value: "gujar khan", label: "Gujar Khan" },
  { value: "kahuta", label: "Kahuta" },
  { value: "kallar syedan", label: "Kallar Syedan" },
  { value: "taxila", label: "Taxila" },
  { value: "daultala", label: "Daultala" },
  { value: "kotli sattian", label: "Kotli Sattian" },
  { value: "murree", label: "Murree" },
  { value: "depalpur", label: "Depalpur" },
  { value: "okara", label: "Okara" },
  { value: "renala khurd", label: "Renala Khurd" },
  { value: "arifwala", label: "Arifwala" },
  { value: "pakpattan", label: "Pakpattan" },
  { value: "chichawatni", label: "Chichawatni" },
  { value: "sahiwal", label: "Sahiwal" },
  { value: "khushab", label: "Khushab" },
  { value: "noorpur thal", label: "Noorpur Thal" },
  { value: "quaidabad", label: "Quaidabad" },
  { value: "naushera(wadi-e-soon)", label: "Naushera (Wadi-e-Soon)" },
  { value: "bhalwal", label: "Bhalwal" },
  { value: "bhera", label: "Bhera" },
  { value: "kot momin", label: "Kot Momin" },
  { value: "sargodha", label: "Sargodha" },
  { value: "shahpur", label: "Shahpur" },
  { value: "sillanwali", label: "Sillanwali" },
  { value: "bhakkar", label: "Bhakkar" },
  { value: "darya khan", label: "Darya Khan" },
  { value: "kaloorkot", label: "Kaloorkot" },
  { value: "mankera", label: "Mankera" },
  { value: "isakhel", label: "Isakhel" },
  { value: "mianwali", label: "Mianwali" },
  { value: "piplan", label: "Piplan" },
  { value: "talagang", label: "Talagang" },
  { value: "lawa", label: "Lawa" },
  { value: "multan khurd", label: "Multan Khurd" },
  { value: "baka khel", label: "Baka Khel" },
  { value: "bannu", label: "Bannu" },
  { value: "domel", label: "Domel" },
  { value: "kakki", label: "Kakki" },
  { value: "miryan", label: "Miryan" },
  { value: "wazir", label: "Wazir" },
  { value: "bettani", label: "Bettani" },
  { value: "ghazni khel", label: "Ghazni Khel" },
  { value: "lakki marwat", label: "Lakki Marwat" },
  { value: "sari naurang", label: "Sari Naurang" },
  { value: "datta khel", label: "Datta Khel" },
  { value: "dossali", label: "Dossali" },
  { value: "gharyum", label: "Gharyum" },
  { value: "ghulam khan", label: "Ghulam Khan" },
  { value: "mir ali", label: "Mir Ali" },
  { value: "miran shah", label: "Miran Shah" },
  { value: "razmak", label: "Razmak" },
  { value: "shewa", label: "Shewa" },
  { value: "spinwam", label: "Spinwam" },
  { value: "daraban", label: "Daraban" },
  { value: "darazinda", label: "Darazinda" },
  { value: "dera ismail khan", label: "Dera Ismail Khan" },
  { value: "kulachi", label: "Kulachi" },
  { value: "paharpur", label: "Paharpur" },
  { value: "paniala", label: "Paniala" },
  { value: "paroa", label: "Paroa" },
  { value: "birmil", label: "Birmil" },
  { value: "shakai", label: "Shakai" },
  { value: "toi khulla", label: "Toi Khulla" },
  { value: "wana", label: "Wana" },
  { value: "ladha", label: "Ladha" },
  { value: "makin", label: "Makin" },
  { value: "sararogha", label: "Sararogha" },
  { value: "sarwakai", label: "Sarwakai" },
  { value: "shaktoi", label: "Shaktoi" },
  { value: "shawal", label: "Shawal" },
  { value: "tiarza", label: "Tiarza" },
  { value: "jandola", label: "Jandola" },
  { value: "tank", label: "Tank" },
  { value: "abbottabad", label: "Abbottabad" },
  { value: "havelian", label: "Havelian" },
  { value: "lora", label: "Lora" },
  { value: "lower tanawal", label: "Lower Tanawal" },
  { value: "allai", label: "Allai" },
  { value: "batagram", label: "Batagram" },
  { value: "ghazi", label: "Ghazi" },
  { value: "haripur", label: "Haripur" },
  { value: "khanpur", label: "Khanpur" },
  { value: "bataira / kolai", label: "Bataira / Kolai" },
  { value: "palas", label: "Palas" },
  { value: "bankad", label: "Bankad" },
  { value: "pattan", label: "Pattan" },
  { value: "baffa pakhal", label: "Baffa Pakhal" },
  { value: "bala kot", label: "Bala Kot" },
  { value: "mansehra", label: "Mansehra" },
  { value: "oghi", label: "Ogri" },
  { value: "tanawal", label: "Tanawal" },
  { value: "daur maira", label: "Daur Maira" },
  { value: "judba", label: "Judba" },
  { value: "khander hassanzai", label: "Khander Hassanzai" },
  { value: "dassu", label: "Dassu" },
  { value: "harban basha", label: "Harban Basha" },
  { value: "kandia", label: "Kandia" },
  { value: "seo", label: "Seo" },
  { value: "doaba", label: "Doaba" },
  { value: "hangu", label: "Hangu" },
  { value: "tall", label: "Tall" },
  { value: "banda daud shah", label: "Banda Daud Shah" },
  { value: "karak", label: "Karak" },
  { value: "takht-e-nasrati", label: "Takht-e-Nasrati" },
  { value: "dara adam khel", label: "Dara Adam Khel" },
  { value: "gumbat", label: "Gumbat" },
  { value: "kohat", label: "Kohat" },
  { value: "lachi", label: "Lachi" },
  { value: "central kurram", label: "Central Kurram" },
  { value: "lower kurram", label: "Lower Kurram" },
  { value: "upper kurram", label: "Upper Kurram" },
  { value: "central orakzai", label: "Central Orakzai" },
  { value: "ismail zai", label: "Ismail Zai" },
  { value: "lower orakzai", label: "Lower Orakzai" },
  { value: "upper orakzai", label: "Upper Orakzai" },
  { value: "bar chamarkand", label: "Bar Chamarkand" },
  { value: "barang", label: "Barang" },
  { value: "khar bajaur", label: "Khar Bajaur" },
  { value: "mamund", label: "Mamund" },
  { value: "nawagai", label: "Nawagai" },
  { value: "salarzai", label: "Salarzai" },
  { value: "utman khel", label: "Utman Khel" },
  { value: "chagharzai", label: "Chagharzai" },
  { value: "daggar", label: "Daggar" },
  { value: "gadezai", label: "Gadezai" },
  { value: "gagra", label: "Gagra" },
  { value: "khudu khel", label: "Khudu Khel" },
  { value: "mandanr", label: "Mandanr" },
  { value: "chitral", label: "Chitral" },
  { value: "drosh", label: "Drosh" },
  { value: "adenzai", label: "Adenzai" },
  { value: "balambat", label: "Balambat" },
  { value: "khal", label: "Khal" },
  { value: "lal qilla", label: "Lal Qilla" },
  { value: "munda", label: "Munda" },
  { value: "samar bagh", label: "Samar Bagh" },
  { value: "timergara", label: "Timergara" },
  { value: "sam ranizai", label: "Sam Ranizai" },
  { value: "swat ranizai", label: "Swat Ranizai" },
  { value: "thana baizai", label: "Thana Baizai" },
  { value: "utman khel", label: "Utman Khel" },
  { value: "alpuri", label: "Alpuri" },
  { value: "bisham", label: "Bisham" },
  { value: "chakesar", label: "Chakesar" },
  { value: "martung", label: "Martung" },
  { value: "makhuzai", label: "Makhuzai" },
  { value: "shahpur", label: "Shahpur" },
  { value: "puran", label: "Puran" },
  { value: "babuzai", label: "Babuzai" },
  { value: "barikot", label: "Barikot" },
  { value: "behrain", label: "Behrain" },
  { value: "charbagh", label: "Charbagh" },
  { value: "kabal", label: "Kabal" },
  { value: "khwaza khela", label: "Khwaza Khela" },
  { value: "matta", label: "Matta" },
  { value: "buni", label: "Buni" },
  { value: "mulkhow", label: "Mulkhow" },
  { value: "torkhow", label: "Torkhow" },
  { value: "mastuj", label: "Mastuj" },
  { value: "barawal", label: "Barawal" },
  { value: "dir", label: "Dir" },
  { value: "kalkot", label: "Kalkot" },
  { value: "lar jam", label: "Lar Jam" },
  { value: "sharingal", label: "Sharingal" },
  { value: "wari", label: "Wari" },
  { value: "ghari kapura", label: "Ghari Kapura" },
  { value: "katlang", label: "Katlang" },
  { value: "mardan", label: "Mardan" },
  { value: "rustam", label: "Rustam" },
  { value: "takht bhai", label: "Takht Bhai" },
  { value: "lahor", label: "Lahor" },
  { value: "razar", label: "Razar" },
  { value: "swabi", label: "Swabi" },
  { value: "topi", label: "Topi" },
  { value: "charsadda", label: "Charsadda" },
  { value: "shabqadar", label: "Shabqadar" },
  { value: "tangi", label: "Tangi" },
  { value: "bagh maidan", label: "Bagh Maidan" },
  { value: "bara", label: "Bara" },
  { value: "bazar zakha khel", label: "Bazar Zakha Khel" },
  { value: "fort salop", label: "Fort Salop" },
  { value: "jamrud", label: "Jamrud" },
  { value: "landi kotal", label: "Landi Kotal" },
  { value: "mula gori", label: "Mula Gori" },
  { value: "painda cheena", label: "Painda Cheena" },
  { value: "ambar utman khel", label: "Ambar Utman Khel" },
  { value: "halim zai", label: "Halim Zai" },
  { value: "pindiali", label: "Pindiali" },
  { value: "pran ghar", label: "Pran Ghar" },
  { value: "safi", label: "Safi" },
  { value: "upper mohmand (baizai)", label: "Upper Mohmand (Baizai)" },
  { value: "yake ghund", label: "Yake Ghund" },
  { value: "jehangira", label: "Jehangira" },
  { value: "nowshera", label: "Nowshera" },
  { value: "pabbi", label: "Pabbi" },
  { value: "badbher", label: "Badbher" },
  { value: "chamkani", label: "Chamkani" },
  { value: "hassan khel", label: "Hassan Khel" },
  { value: "mathra", label: "Mathra" },
  { value: "peshawar city", label: "Peshawar City" },
  { value: "peshtakhara", label: "Peshtakhara" },
  { value: "shah alam", label: "Shah Alam" },
  { value: "badin", label: "Badin" },
  { value: "khoski", label: "Khoski" },
  { value: "matli", label: "Matli" },
  { value: "shaheed fazil rahu", label: "Shaheed Fazil Rahu" },
  { value: "talhar", label: "Talhar" },
  { value: "tando bago", label: "Tando Bago" },
  { value: "jati", label: "Jati" },
  { value: "kharo chan", label: "Kharo Chan" },
  { value: "mirpur bathoro", label: "Mirpur Bathoro" },
  { value: "shah bandar", label: "Shah Bandar" },
  { value: "sujawal", label: "Sujawal" },
  { value: "ghorabari", label: "Ghorabari" },
  { value: "keti bunder", label: "Keti Bunder" },
  { value: "mirpur sakro", label: "Mirpur Sakro" },
  { value: "thatta", label: "Thatta" },
  { value: "dadu", label: "Dadu" },
  { value: "johi", label: "Johi" },
  { value: "khairpur nathan shah", label: "Khairpur Nathan Shah" },
  { value: "mehar", label: "Mehar" },
  { value: "hyderabad city", label: "Hyderabad City" },
  { value: "hyderabad", label: "Hyderabad" },
  { value: "latifabad", label: "Latifabad" },
  { value: "qasimabad", label: "Qasimabad" },
  { value: "kotri", label: "Kotri" },
  { value: "sehwan", label: "Sehwan" },
  { value: "manjhand", label: "Manjhand" },
  { value: "thana bulla khan", label: "Thana Bulla Khan" },
  { value: "hala", label: "Hala" },
  { value: "matiari", label: "Matiari" },
  { value: "saeedabad", label: "Saeedabad" },
  { value: "darband", label: "Darband" },
  { value: "chamber", label: "Chamber" },
  { value: "jhando mari", label: "Jhando Mari" },
  { value: "tando allahyar", label: "Tando Allahyar" },
  { value: "nasarpur", label: "Nasarpur" },
  { value: "bulri shah karim", label: "Bulri Shah Karim" },
  { value: "tando ghulam hyder", label: "Tando Ghulam Hyder" },
  { value: "tando mohammad khan", label: "Tando Mohammad Khan" },
  { value: "gulberg town", label: "Gulberg Town" },
  { value: "liaquatabad town", label: "Liaquatabad Town" },
  { value: "new karachi town", label: "New Karachi Town" },
  { value: "north nazimabad town", label: "North Nazimabad Town" },
  { value: "nazimabad", label: "Nazimabad" },
  { value: "north karachi", label: "North Karachi" },
  { value: "gulistan-e-jouhar (g-e-j)", label: "Gulistan-e-Jouhar (G-E-J)" },
  { value: "gulshan town", label: "Gulshan Town" },
  { value: "jamshed town", label: "Jamshed Town" },
  { value: "ferozabad", label: "Ferozabad" },
  { value: "gulshan-e-iqbal", label: "Gulshan-e-Iqbal" },
  { value: "gulzar-e-hijri", label: "Gulzar-e-Hijri" },
  { value: "lyari town", label: "Lyari Town" },
  { value: "saddar town", label: "Saddar Town" },
  { value: "aram bagh", label: "Aram Bagh" },
  { value: "civil line", label: "Civil Line" },
  { value: "garden", label: "Garden" },
  { value: "orangi town", label: "Orangi Town" },
  { value: "manghopir", label: "Manghopir" },
  { value: "maripur", label: "Maripur" },
  { value: "mominabad", label: "Mominabad" },
  { value: "ittehad town", label: "Ittehad Town" },
  { value: "baldia town", label: "Baldia Town" },
  { value: "korangi town", label: "Korangi Town" },
  { value: "landhi town", label: "Landhi Town" },
  { value: "shah faisal town", label: "Shah Faisal Town" },
  { value: "model colony", label: "Model Colony" },
  { value: "bin qasim town", label: "Bin Qasim Town" },
  { value: "gadap town", label: "Gadap Town" },
  { value: "malir town", label: "Malir Town" },
  { value: "jinnah", label: "Jinnah" },
  { value: "ibrahim hyderi", label: "Ibrahim Hyderi" },
  { value: "murad memon", label: "Murad Memon" },
  { value: "shah murad", label: "Shah Murad" },
  { value: "keamari town", label: "Keamari Town" },
  { value: "baldia town", label: "Baldia Town" },
  { value: "s.i.t.e. town", label: "S.I.T.E. Town" },
  { value: "karachi fish harbour", label: "Karachi Fish Harbour" },
  { value: "garhi khairo", label: "Garhi Khairo" },
  { value: "jacobabad", label: "Jacobabad" },
  { value: "thul", label: "Thul" },
  { value: "kandhkot", label: "Kandhkot" },
  { value: "kashmore", label: "Kashmore" },
  { value: "tangwani", label: "Tangwani" },
  { value: "bakrani", label: "Bakrani" },
  { value: "dokri", label: "Dokri" },
  { value: "larkana", label: "Larkana" },
  { value: "ratodero", label: "Ratodero" },
  { value: "mirokhan", label: "Mirokhan" },
  { value: "nasirabad", label: "Nasirabad" },
  { value: "qambar", label: "Qambar" },
  { value: "qubo saeed khan", label: "Qubo Saeed Khan" },
  { value: "shahdadkot", label: "Shahdadkot" },
  { value: "sijawal junejo", label: "Sijawal Junejo" },
  { value: "warah", label: "Warah" },
  { value: "garhi yasin", label: "Garhi Yasin" },
  { value: "khanpur", label: "Khanpur" },
  { value: "lakhi", label: "Lakhi" },
  { value: "shikarpur", label: "Shikarpur" },
  { value: "digri", label: "Digri" },
  { value: "jhuddo", label: "Jhuddo" },
  { value: "kot ghulam muhammad", label: "Kot Ghulam Muhammad" },
  { value: "mirpur khas", label: "Mirpur Khas" },
  { value: "shujabad", label: "Shujabad" },
  { value: "sindhri", label: "Sindhri" },
  { value: "chachro", label: "Chachro" },
  { value: "dahli", label: "Dahli" },
  { value: "diplo", label: "Diplo" },
  { value: "kaloi", label: "Kaloi" },
  { value: "islamkot", label: "Islamkot" },
  { value: "mithi", label: "Mithi" },
  { value: "nagarparkar", label: "Nagarparkar" },
  { value: "kunri", label: "Kunri" },
  { value: "pithoro", label: "Pithoro" },
  { value: "samaro", label: "Samaro" },
  { value: "umerkot", label: "Umerkot" },
  { value: "daharki", label: "Daharki" },
  { value: "ghotki", label: "Ghotki" },
  { value: "mirpur mathelo", label: "Mirpur Mathelo" },
  { value: "ubauro", label: "Ubauro" },
  { value: "faiz ganj", label: "Faiz Ganj" },
  { value: "gambat", label: "Gambat" },
  { value: "kingri", label: "Kingri" },
  { value: "kot diji", label: "Kot Diji" },
  { value: "nara", label: "Nara" },
  { value: "sobho dero", label: "Sobho Dero" },
  { value: "thari mirwah", label: "Thari Mirwah" },
  { value: "new sukkur", label: "New Sukkur" },
  { value: "pano aqil", label: "Pano Aqil" },
  { value: "rohri", label: "Rohri" },
  { value: "salehpat", label: "Salehpat" },
  { value: "sukkur", label: "Sukkur" },
  { value: "bhiria", label: "Bhiria" },
  { value: "kandiaro", label: "Kandiaro" },
  { value: "mehrabpur", label: "Mehrabpur" },
  { value: "moro", label: "Moro" },
  { value: "naushahro feroze", label: "Naushahro Feroze" },
  { value: "jam nawaz ali", label: "Jam Nawaz Ali" },
  { value: "khipro", label: "Khipro" },
  { value: "sanghar", label: "Sanghar" },
  { value: "shahdadpur", label: "Shahdadpur" },
  { value: "sinjhoro", label: "Sinjhoro" },
  { value: "tando adam khan", label: "Tando Adam Khan" },
  { value: "bori", label: "Bori" },
  { value: "mekhtar", label: "Mekhtar" },
  { value: "duki", label: "Duki" },
  { value: "darug", label: "Darug" },
  { value: "kingri", label: "Kingri" },
  { value: "musakhel", label: "Musakhel" },
  { value: "toisar", label: "Toisar" },
  { value: "awaran", label: "Awaran" },
  { value: "gishkaur", label: "Gishkaur" },
  { value: "jhal jhao", label: "Jhal Jhao" },
  { value: "korak jahoo", label: "Korak Jahoo" },
  { value: "mashkay", label: "Mashkay" },
  { value: "kalat", label: "Kalat" },
  { value: "mangochar", label: "Mangochar" },
  { value: "surab", label: "Surab" },
  { value: "gazg", label: "Gazg" },
  { value: "johan", label: "Johan" },
  { value: "kharan", label: "Kharan" },
  { value: "khangarh (khanpur)", label: "Khangarh (Khanpur)" },
  { value: "khairpur", label: "Khairpur" },
  { value: "nawabshah", label: "Nawabshah" },
  { value: "sar-kharan", label: "Sar-Kharan" },
  { value: "tohumulk", label: "Tohumulk" },
  { value: "khuzdar", label: "Khuzdar" },
  { value: "wadh", label: "Wadh" },
  { value: "zehri", label: "Zehri" },
  { value: "baghbana", label: "Baghbana" },
  { value: "aranji", label: "Aranji" },
  { value: "greshek", label: "Greshek" },
  { value: "karkh", label: "Karkh" },
  { value: "moola", label: "Moola" },
  { value: "ornach", label: "Ornach" },
  { value: "saroona", label: "Saroona" },
  { value: "hub", label: "Hub" },
  { value: "dureji", label: "Dureji" },
  { value: "bela", label: "Bela" },
  { value: "kanraj", label: "Kanraj" },
  { value: "uthal", label: "Uthal" },
  { value: "mastung", label: "Mastung" },
  { value: "khad koocha", label: "Khad Koocha" },
  { value: "kardigap", label: "Kardigap" },
  { value: "besima", label: "Besima" },
  { value: "mashkel", label: "Mashkel" },
  { value: "washuk", label: "Washuk" },
  { value: "nag", label: "Nag" },
  { value: "shahgori", label: "Shahgori" },
  { value: "gwadar", label: "Gwadar" },
  { value: "jiwani", label: "Jiwani" },
  { value: "ormara", label: "Ormara" },
  { value: "pasni", label: "Pasni" },
  { value: "suntsar", label: "Suntsar" },
  { value: "mand", label: "Mand" },
  { value: "tump", label: "Tump" },
  { value: "turbat", label: "Turbat" },
  { value: "balnigor", label: "Balnigor" },
  { value: "buleda", label: "Buleda" },
  { value: "dasht", label: "Dasht" },
  { value: "zamuran", label: "Zamuran" },
  { value: "gayab", label: "Gayab" },
  { value: "solband", label: "Solband" },
  { value: "gowargo", label: "Gowargo" },
  { value: "panjgur", label: "Panjgur" },
  { value: "paroom", label: "Paroom" },
  { value: "gichk", label: "Gichk" },
  { value: "gandakha", label: "Gandakha" },
  { value: "jhatpat", label: "Jhatpat" },
  { value: "usta mohammad", label: "Usta Mohammad" },
  { value: "gandawa", label: "Gandawa" },
  { value: "jhal magsi", label: "Jhal Magsi" },
  { value: "mirpur", label: "Mirpur" },
  { value: "dhadar", label: "Dhadar" },
  { value: "balanari", label: "Balanari" },
  { value: "khattan", label: "Khattan" },
  { value: "mach", label: "Mach" },
  { value: "sani", label: "Sani" },
  { value: "bhag", label: "Bhag" },
  { value: "lehri", label: "Lehri" },
  { value: "baba kot", label: "Baba Kot" },
  { value: "dera murad jamali", label: "Dera Murad Jamali" },
  { value: "tamboo", label: "Tamboo" },
  { value: "chattar", label: "Chattar" },
  { value: "faridabad", label: "Faridabad" },
  { value: "hayrvi", label: "Hayrvi" },
  { value: "manjipur", label: "Manjipur" },
  { value: "sohbatpur", label: "Sohbatpur" },
  { value: "dalbandin", label: "Dalbandin" },
  { value: "nokundi", label: "Nokundi" },
  { value: "taftan", label: "Taftan" },
  { value: "chagai", label: "Chagai" },
  { value: "chaman", label: "Chaman" },
  { value: "gulistan", label: "Gulistan" },
  { value: "killa abdullah", label: "Killa Abdullah" },
  { value: "dobandi", label: "Dobandi" },
  { value: "nushki", label: "Nushki" },
  { value: "dak", label: "Dak" },
  { value: "barshore", label: "Barshore" },
  { value: "hurramzai", label: "Hurramzai" },
  { value: "karezat", label: "Karezat" },
  { value: "khanozai", label: "Khanozai" },
  { value: "pishin", label: "Pishin" },
  { value: "saranan", label: "Saranan" },
  { value: "chiltan", label: "Chiltan" },
  { value: "zarghoon", label: "Zarghoon" },
  { value: "panjpai", label: "Panjpai" },
  { value: "sadar", label: "Sadar" },
  { value: "dera bugti", label: "Dera Bugti" },
  { value: "phelawagh", label: "Phelawagh" },
  { value: "sui", label: "Sui" },
  { value: "baiker", label: "Baiker" },
  { value: "harnai", label: "Harnai" },
  { value: "shahrig", label: "Shahrig" },
  { value: "khoast", label: "Khoast" },
  { value: "kahan", label: "Kahan" },
  { value: "kohlu", label: "Kohlu" },
  { value: "maiwand", label: "Maiwand" },
  { value: "tamboo", label: "Tamboo" },
  { value: "grisini", label: "Grisini" },
  { value: "sibi", label: "Sibi" },
  { value: "kutmandai", label: "Kutmandai" },
  { value: "sangan", label: "Sangan" },
  { value: "ziarat", label: "Ziarat" },
  { value: "sinjavi", label: "Sinjavi" },
  { value: "sherani", label: "Sherani" },
  { value: "qamar din karez", label: "Qamar Din Karez" },
  { value: "zhob", label: "Zhob" },
  { value: "ashwat", label: "Ashwat" },
  { value: "kashatu", label: "Kashatu" },
  { value: "sambaza", label: "Sambaza" },
  { value: "killa saifullah", label: "Killa Saifullah" },
  { value: "loiband", label: "Loiband" },
  { value: "muslim bagh", label: "Muslim Bagh" },
  { value: "badini", label: "Badini" },
  { value: "kanmetharzai", label: "Kanmetharzai" },
  { value: "shinki", label: "Shinki" },
  { value: "barkhan", label: "Barkhan" },
  { value: "kotli", label: "Kotli" },
  { value: "khuiratta", label: "Khuiratta" },
  { value: "fatehpur thakiala", label: "Fatehpur Thakiala" },
  { value: "sehnsa", label: "Sehnsa" },
  { value: "charhoi", label: "Charhoi" },
  { value: "duliah jattan", label: "Duliah Jattan" },
  { value: "dadyal", label: "Dadyal" },
  { value: "mirpur", label: "Mirpur" },
  { value: "islamgarh", label: "Islamgarh" },
  { value: "bhimber", label: "Bhimber" },
  { value: "barnala", label: "Barnala" },
  { value: "samahni", label: "Samahni" },
  { value: "hattian bala", label: "Hattian Bala" },
  { value: "chikkar", label: "Chikkar" },
  { value: "leepa", label: "Leepa" },
  { value: "muzaffarabad", label: "Muzaffarabad" },
  { value: "nasirbad", label: "Nasirbad" },
  { value: "naal", label: "Naal" },
  { value: "meer hassan", label: "Meer Hassan" },
  { value: "athmuqam", label: "Athmuqam" },
  { value: "sharda", label: "Sharda" },
  { value: "bagh", label: "Bagh" },
  { value: "dhirkot", label: "Dhirkot" },
  { value: "hari ghel", label: "Hari Ghel" },
  { value: "rera", label: "Rera" },
  { value: "birpani", label: "Birpani" },
  { value: "haveli", label: "Haveli" },
  { value: "khurshidabad", label: "Khurshidabad" },
  { value: "mumtazabad", label: "Mumtazabad" },
  { value: "abbaspur", label: "Abbaspur" },
  { value: "hajira", label: "Hajira" },
  { value: "rawalakot", label: "Rawalakot" },
  { value: "thorar", label: "Thorar" },
  { value: "balouch", label: "Balouch" },
  { value: "mang", label: "Mang" },
  { value: "pallandri", label: "Pallandri" },
  { value: "tarar khel", label: "Tarar Khel" },
  { value: "gupis", label: "Gupis" },
  { value: "yasin", label: "Yasin" },
  { value: "phander", label: "Phander" },
  { value: "aliabad", label: "Aliabad" },
  { value: "gojal", label: "Gojal" },
  { value: "nagar-i", label: "Nagar-I" },
  { value: "nagar-ii", label: "Nagar-II" },
  { value: "chalt", label: "Chalt" },
  { value: "gultari", label: "Gultari" },
  { value: "kharmang", label: "Kharmang" },
  { value: "tolti", label: "Tolti" },
  { value: "dasht mastung", label: "Dasht Mastung" },
  { value: "qazi ahmed", label: "Qazi Ahmed" },
  { value: "sakrand", label: "Sakrand" },
  { value: "daur", label: "Daur" },
  { value: "doulatpur", label: "Doulatpur" },
  { value: "kot chutta", label: "Kot Chutta" },
];

export const facilitiesFilterOptions = [
  { id: "canal", label: "Canal" },
  { id: "electricity", label: "Electricity" },
  { id: "road", label: "Road" },
  { id: "tubewell", label: "Tubewell" },
  { id: "well", label: "Well" },
];

export const landTypeFilterOptions = [
  { id: "irrigated", label: "Irrigated" },
  { id: "rainfed", label: "Rainfed" },
];

export const cropsFilteringOptions = [
  { value: "barley", label: "Barley" },
  { value: "bottle gourd", label: "Bottle Gourd" },
  { value: "broccoli", label: "Broccoli" },
  { value: "canary seed", label: "Canary Seed" },
  { value: "canola", label: "Canola" },
  { value: "carrot", label: "Carrot" },
  { value: "chickpea kabuli", label: "Chickpea Kabuli" },
  { value: "coriander", label: "Coriander" },
  { value: "cotton", label: "Cotton" },
  { value: "cucumber", label: "Cucumber" },
  { value: "flax seed", label: "Flax Seed" },
  { value: "french beans", label: "French Beans" },
  { value: "kidney beans", label: "Kidney Beans" },
  { value: "lentil", label: "Lentil" },
  { value: "maize", label: "Maize" },
  { value: "mash", label: "Mash" },
  { value: "millet", label: "Millet" },
  { value: "mustard", label: "Mustard" },
  { value: "oat", label: "Oat" },
  { value: "okra", label: "Okra" },
  { value: "pea", label: "Pea" },
  { value: "peanut", label: "Peanut" },
  { value: "potato", label: "Potato" },
  { value: "radish", label: "Radish" },
  { value: "sesame", label: "Sesame" },
  { value: "sorghum", label: "Sorghum" },
  { value: "soybean", label: "Soybean" },
  { value: "sponge gourd", label: "Sponge Gourd" },
  { value: "sugar beet", label: "Sugar Beet" },
  { value: "sunflower", label: "Sunflower" },
  { value: "tinda gourd", label: "Tinda Gourd" },
  { value: "turnip", label: "Turnip" },
  { value: "vegetable marrow(squash)", label: "Vegetable Marrow (Squash)" },
  { value: "watermelon", label: "Watermelon" },
  { value: "wheat", label: "Wheat" },
];

export const pricesFilteringOptions = [
  { value: "0-500000", label: "Upto 5 Lakh" },
  { value: "500000-1000000", label: "5 Lakh - 10 Lakh" },
  { value: "1000000-2000000", label: "10 Lakh - 20 Lakh" },
  { value: "2000000-10000000", label: "20 Lakh - 1 Crore" },
  { value: "10000000-", label: "1 Crore and above" },
];

export const navItems = [
  {
    title: "Dashboard",
    url: "/dashboard/overiew",
    icon: "dashboard",
    isActive: false,
    shortcut: ["d", "d"],
    items: [],
  },
  {
    title: "Contract Farming",
    url: "/dashboard/contract-farming",
    icon: "product",
    shortcut: ["p", "p"],
    isActive: false,
    items: [],
  },
  {
    title: "Account",
    url: "#",
    icon: "billing",
    isActive: true,

    items: [
      {
        title: "Profile",
        url: "/dashboard/settings",
        icon: "userPen",
        shortcut: ["m", "m"],
      },
    ],
  },
];
